[package]
name = "ga_lib"
version = "0.1.0"
edition = "2021"
authors = [ "Rasmus Enevoldsen" ]
readme = "README.org"
license = "GPL-3.0-or-later"

[dependencies]
libm = {version = "0.2.11"} # math lib for embedded
approx = {version = "0.5.1"} # approx test for floats

[package.metadata.docs.rs]
rustdoc-args = [
"--html-in-header", "./katex-header.html"
]
